# syntax=docker/dockerfile:experimental

FROM node:14.3.0 AS build-frontend
WORKDIR /src
COPY betanin_client .
RUN --mount=type=cache,target=/root/.npm \
    --mount=type=cache,target=/src/node_modules \
    npm install && npm run-script build

FROM python:3.6.6-alpine3.6
LABEL maintainer="Senan Kelly <senan@senan.xyz>"
RUN apk add --no-cache libev build-base libffi-dev
COPY ./requirements-docker.txt /
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -U \
        https://github.com/caronc/apprise/archive/master.zip \
        -r /requirements-docker.txt
WORKDIR /src
RUN mkdir betanin_client
COPY --from=build-frontend /src/dist/ betanin_client/dist/
COPY . .
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -U -e .
VOLUME [ \
    "/root/.local/share/betanin/" \
    "/root/.config/betanin/" \
    "/root/.config/beets/" \
]
ENV \
    PYTHONUNBUFFERED=1 \
    PYTHONWARNINGS="ignore:Unverified HTTPS request"
CMD [ "betanin" ]
